name: Deploy User Service a AWS

on:
  push:
    branches:
      - deploy

jobs:
  build-and-push-aws:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repo
        uses: actions/checkout@v4

      - name: Configurar credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Iniciar sesion en Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Construir y publicar imagen en ECR
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/backend1user:latest
            ${{ steps.login-ecr.outputs.registry }}/backend1user:${{ github.sha }}